class AppColors:

	PRIMARY = "#0A3BFF"
	SECONDARY = "#00B86B"
	ACCENT = "#EAFBFF"
	SURFACE = "#151A2E"
	HIGHLIGHT = "#C400FF"

	BACKGROUND = "#090B14"
	CARD = SURFACE
	TEXT_PRIMARY = ACCENT
	TEXT_SECONDARY = "#8FB3C1"
	BORDER = PRIMARY

	SUCCESS = PRIMARY
	WARNING = "#FFD400"
	ERROR = "#E63946"

	BUTTON_PRIMARY_BG = PRIMARY
	BUTTON_SECONDARY_BG = HIGHLIGHT
	BUTTON_NEUTRAL_BG = "#1A2238"
	BUTTON_DANGER_BG = ERROR
	BUTTON_TEXT = "#F5FCFF"

	GLOW_PRIMARY = "#660A3BFF"
	GLOW_SECONDARY = "#6600B86B"
	GLOW_HIGHLIGHT = "#66C400FF"
